test

diff --git a/nextflow b/nextflow
--- a/nextflow
+++ b/nextflow
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-#  Copyright 2013-2018, Centre for Genomic Regulation (CRG)
+#  Copyright 2013-2023, Seqera Labs
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
 #  you may not use this file except in compliance with the License.
@@ -15,13 +15,16 @@
 #  limitations under the License.
 
 [[ "$NXF_DEBUG" == 'x' ]] && set -x
-NXF_VER=${NXF_VER:-'18.10.1'}
+NXF_VER=${NXF_VER:-'23.09.3-edge'}
 NXF_ORG=${NXF_ORG:-'nextflow-io'}
 NXF_HOME=${NXF_HOME:-$HOME/.nextflow}
 NXF_PROT=${NXF_PROT:-'https'}
 NXF_BASE=${NXF_BASE:-$NXF_PROT://www.nextflow.io/releases}
 NXF_TEMP=${NXF_TEMP:-$TMPDIR}
+NXF_DIST=${NXF_DIST:-$NXF_HOME/framework}
 NXF_CLI="$0 $@"
+NXF_CLI_OPTS=${NXF_CLI_OPTS:-}
+NXF_REMOTE_DEBUG_PORT=${NXF_REMOTE_DEBUG_PORT:-5005}
 
 export NXF_CLI
 export NXF_ORG
@@ -61,7 +64,7 @@ function get() {
     if command -v curl &>/dev/null; then
         GET="curl -fsSL '$1' -o '$2'"
     elif command -v wget &>/dev/null; then
-        GET="wget -q '$1' -O '$2'"
+        GET="wget '$1' -O '$2' >/dev/null 2>&1"
     else
         echo_red "ERROR: Cannot find 'curl' nor 'wget' utility --  please install one of them"
         exit 1
@@ -83,6 +86,17 @@ function get() {
     fi
 }
 
+function get_ver() {
+    if command -v curl &>/dev/null; then
+        curl -fsSL "$1"
+    elif command -v wget &>/dev/null; then
+        wget "$1" >/dev/null 2>&1
+    else
+        echo_red "ERROR: Cannot find 'curl' nor 'wget' utility -- please install one of them"
+        exit 1
+    fi
+}
+
 function make_temp() {
     local base=${NXF_TEMP:=$PWD}
     if [ "$(uname)" = 'Darwin' ]; then mktemp "${base}/nxf-tmp.XXXXXX" || exit $?
@@ -96,10 +110,10 @@ function resolve_link() {
       realpath "$1"
     elif command -v readlink &>/dev/null; then
       local target="$1"
-      cd $(dirname $target); target=$(basename $target)
+      cd "$(dirname "$target")"; target="$(basename "$target")"
       while [ -L "$target" ]; do
         target="$(readlink "$target")"
-        cd $(dirname $target); target=$(basename $target)
+        cd "$(dirname "$target")"; target="$(basename "$target")"
       done
       echo "$(cd "$(dirname "$target")"; pwd -P)/$target"
     else
@@ -108,9 +122,13 @@ function resolve_link() {
     fi
 }
 
+function current_ver() {
+  [[ $NXF_EDGE == 1 || $NXF_VER == *"-edge" ]] && printf 'edge' || printf 'latest'
+}
+
 function install() {
     local tmpfile=$(make_temp)
-    local version=$(set +u; [[ $NXF_VER ]] && printf "v$NXF_VER" || printf 'latest')
+    local version=$(set +u; [[ $NXF_VER ]] && printf "v$NXF_VER" || current_ver)
     local action="a=${2:-default}"
     get "$NXF_BASE/$version/nextflow?$action" "$tmpfile" "$1" || exit $?
     mv "$tmpfile" "$1" || exit $?
@@ -125,38 +143,26 @@ function install() {
     echo ''
 }
 
+function check_latest() {
+    [[ $cmd != run ]] && return 0
+    [[ $NXF_OFFLINE == true || $NXF_DISABLE_CHECK_LATEST == true ]] && return 0
+    local latest=$(get_ver "$NXF_BASE/$(current_ver)/version?current=$NXF_VER")
+    if [[ -n "$latest" && "$latest" != $NXF_VER ]]; then
+      echo_yellow "Nextflow $latest is available - Please consider updating your version to it"
+    fi
+}
+
 function launch_nextflow() {
     # the launch command line
     local cmdline=()
-    # remove leading and trailing double-quotes 
+    # remove leading and trailing double-quotes
     for x in "${launcher[@]}"; do
         x="${x%\"}"
         x="${x#\"}"
         cmdline+=("$x") 
     done 
 
-    if [[ $NXF_MPIRUN ]]; then
-        local rank=''
-        [[ $SLURM_PROCID ]] && rank=$SLURM_PROCID
-        [[ $OMPI_COMM_WORLD_RANK ]] && rank=$OMPI_COMM_WORLD_RANK
-        if [[ ! $rank ]]; then
-          echo_red 'It looks you are not running in a MPI enabled environment -- cannot find `$OMPI_COMM_WORLD_RANK` nor `$SLURM_PROCID` variable';
-          exit 1;
-        fi
-        if [[ $SLURM_CPUS_PER_TASK && $SLURM_MEM_PER_CPU ]]; then
-            export NXF_CLUSTER_MAXCPUS=$SLURM_CPUS_PER_TASK
-            export NXF_CLUSTER_MAXMEMORY="$(($SLURM_MEM_PER_CPU*$SLURM_CPUS_PER_TASK))MB"
-        fi
-        if [[ $rank == 0 ]]; then
-            # sleep a few seconds in order to wait worker daemons to bootstrap
-            sleep ${NXF_SLEEP:-10}
-            export NXF_EXECUTOR='ignite'
-            export NXF_CLUSTER_SHUTDOWNONCOMPLETE='true'
-        else
-            args=(-log .nextflow_node_${rank}.log node ignite)
-        fi
-    # start in daemon mode
-    elif [[ "$bg" ]]; then
+    if [[ "$bg" ]]; then
       local pid_file="${NXF_PID_FILE:-.nextflow.pid}"
       cmdline+=("${args[@]}")
       exec "${cmdline[@]}" &
@@ -171,7 +177,7 @@ function launch_nextflow() {
 }
 
 # check self-install
-if [ "$0" = "bash" ] || [ "$0" = "/bin/bash" ]; then
+if [ "$0" = "bash" ] || [[ "$0" =~ .*/bash ]]; then
     if [ -d nextflow ]; then
         echo 'Please note:'
         echo "- The install procedure needs to create a file named 'nextflow' in this folder, but a directory with this name already exists."
@@ -183,13 +189,19 @@ if [ "$0" = "bash" ] || [ "$0" = "/bin/bash" ]; then
     exit 0
 fi
 
+# clean up env
+# see https://github.com/nextflow-io/nextflow/issues/1716
+unset JAVA_TOOL_OPTIONS
 
 # parse the command line
 bg=''
-dockerize=''
 declare -a jvmopts=()
 declare -a args=("$@")
 declare -a commands=(clone config drop help history info ls pull run view node console kuberun)
+# $NXF_CLI_OPTS allow to pass arbitrary cli opts via the environment
+# note: do not wrap with quotes because the variable can be used to specify more than on option separate by blanks
+[ "$NXF_CLI_OPTS" ] && args+=($NXF_CLI_OPTS)
+
 cmd=''
 while [[ $# != 0 ]]; do
     case $1 in
@@ -198,38 +210,27 @@ while [[ $# != 0 ]]; do
       jvmopts+=("$1")
       fi
       ;;
-    -d|-dockerize)
-      if [[ ! "$cmd" && ! -f /.nextflow/dockerized ]]; then
-      dockerize=1
-      fi
-      ;;
     -bg)
-      if [[ ! -f /.nextflow/dockerized ]]; then
       bg=1
-      fi
+      ;;
+    -remote-debug)
+      echo_yellow "Enabling script debugging - continue the execution launching the remote VM debugger in your favourite IDE using port $NXF_REMOTE_DEBUG_PORT"
+      remote_debug=1
       ;;
     -download)
       if [[ ! "$cmd" ]]; then
-      rm -rf "$NXF_HOME/framework/$NXF_VER" || exit $?
+      rm -rf "$NXF_DIST/$NXF_VER" || exit $?
       bash "$0" -version || exit $?
       exit 0
       fi
       ;;
     -self-update|self-update)
       if [[ ! "$cmd" ]]; then
+      [[ -z $NXF_EDGE && $NXF_VER = *-edge ]] && NXF_EDGE=1
       unset NXF_VER
       install "$0" update
       exit 0
       fi
-      ;;
-    -process.executor|-executor.name)
-      if [[ $2 && $2 == 'ignite' ]]; then
-      NXF_MODE='ignite'; shift;
-      fi
-      ;;
-    -with-mpi)
-      NXF_MODE='ignite'
-      NXF_MPIRUN='true'
       ;;
     *)
       [[ $1 && $1 != -* && ! "$cmd" && ${commands[*]} =~ $1 ]] && cmd=$1
@@ -238,19 +239,6 @@ while [[ $# != 0 ]]; do
     shift
 done
 
-NXF_DOCKER_OPTS=${NXF_DOCKER_OPTS:=''}
-if [[ "$dockerize" ]]; then
-  if [[ "$bg" ]]; then detach='--detach '; else detach=''; fi
-  NXF_ASSETS=${NXF_ASSETS:-${NXF_HOME:-$HOME/.nextflow}/assets}
-  mkdir -p "$NXF_ASSETS"
-  exec docker run $detach --rm --net host \
-   -e USER -e HOME -e NXF_ASSETS=$NXF_ASSETS -e NXF_USRMAP=$(id -u) -e NXF_DOCKER_OPTS='-u $(id -u)' \
-   -v /var/run/docker.sock:/var/run/docker.sock \
-   -v $HOME:$HOME:ro,Z -v $NXF_ASSETS:$NXF_ASSETS:Z -v $PWD:$PWD:Z -w $PWD $NXF_DOCKER_OPTS \
-   nextflow/nextflow:$NXF_VER nextflow "${args[@]}"
-  exit 1
-fi
-
 CAPSULE_LOG=${CAPSULE_LOG:=''}
 CAPSULE_RESET=${CAPSULE_RESET:=''}
 CAPSULE_CACHE_DIR=${CAPSULE_CACHE_DIR:="$NXF_HOME/capsule"}
@@ -258,21 +246,13 @@ CAPSULE_CACHE_DIR=${CAPSULE_CACHE_DIR:="$NXF_HOME/capsule"}
 NXF_PACK=one
 NXF_MODE=${NXF_MODE:-''}
 NXF_JAR=${NXF_JAR:-nextflow-$NXF_VER-$NXF_PACK.jar}
-NXF_BIN=${NXF_BIN:-$NXF_HOME/framework/$NXF_VER/$NXF_JAR}
+NXF_BIN=${NXF_BIN:-$NXF_DIST/$NXF_VER/$NXF_JAR}
 NXF_PATH=$(dirname "$NXF_BIN")
 NXF_URL=${NXF_URL:-$NXF_BASE/v$NXF_VER/$NXF_JAR}
 NXF_GRAB=${NXF_GRAB:-''}
 NXF_CLASSPATH=${NXF_CLASSPATH:-''}
-NXF_MPIRUN=${NXF_MPIRUN:=''}
 NXF_HOST=${HOSTNAME:-localhost}
 [[ $NXF_LAUNCHER ]] || NXF_LAUNCHER=${NXF_HOME}/tmp/launcher/nextflow-${NXF_PACK}_${NXF_VER}/${NXF_HOST}
-
-if [[ $NXF_MODE == ignite ]]; then
-    # Fix JDK bug when there's a limit on the OS virtual memory
-    # https://bugs.openjdk.java.net/browse/JDK-8044054
-    # https://issues.apache.org/jira/browse/HADOOP-7154
-    export MALLOC_ARENA_MAX=4
-fi
 
 # Determine the path to this file
 if [[ $NXF_PACK = all ]]; then
@@ -295,7 +275,7 @@ if [ ! -x "$JAVA_CMD" ] ; then
             JAVA_CMD="$JAVA_HOME/bin/java"
         fi
     elif [ -x /usr/libexec/java_home ]; then
-        JAVA_CMD="$(/usr/libexec/java_home -v 1.8)/bin/java"
+        JAVA_CMD="$(/usr/libexec/java_home -v 1.8+)/bin/java"
     else
         JAVA_CMD="$(which java)" || JAVA_CMD=java
     fi
@@ -320,12 +300,13 @@ else
   fi
   major=${BASH_REMATCH[1]}
   minor=${BASH_REMATCH[2]}
-  version_check="^(1.8|9|10|11)"
-  version_message="Java 8"
   # legacy version - Java 7/8 only
   if [ $major -eq 0 ] && [ $minor -lt 26 ]; then
     version_check="^(1.7|1.8)"
     version_message="Java 7 or 8"
+  else
+    version_check="^(1.8|9|10|11|12|13|14|15|16|17|18|19|20|21)"
+    version_message="Java 8 or later (up to 21)"
   fi
   if [[ ! $JAVA_VER =~ $version_check ]]; then
       echo_red "ERROR: Cannot find Java or it's a wrong version -- please make sure that $version_message is installed"
@@ -335,6 +316,9 @@ else
       echo_yellow "NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:\n JAVA_CMD: $JAVA_CMD\n JAVA_HOME: $JAVA_HOME\n"
       fi
       exit 1
+  fi
+  if [[ ! $JAVA_VER =~ ^(11|12|13|14|15|16|17|18|19|20|21) ]]; then
+      echo_yellow "NOTE: Nextflow is not tested with Java $JAVA_VER -- It's recommended the use of version 11 up to 21\n"
   fi
   mkdir -p $(dirname "$JAVA_KEY")
   [[ -f $JAVA_VER ]] && echo $JAVA_VER > "$JAVA_KEY"
@@ -349,17 +333,14 @@ if [ ! -f "$NXF_BIN" ]; then
     mv "$tmpfile" "$NXF_BIN"
 fi
 
-[[ "$cmd" == "console" ]] && NXF_MODE='console'
-[[ "$cmd" == "node" && ! "$NXF_MODE" ]] && NXF_MODE='ignite'
-
 COLUMNS=${COLUMNS:-`tty -s && tput cols 2>/dev/null || true`}
 declare -a JAVA_OPTS=()
-JAVA_OPTS+=(-Dfile.encoding=UTF-8 -noverify -Dcapsule.trampoline -Dcapsule.java.cmd="$JAVA_CMD")
+JAVA_OPTS+=(-Dfile.encoding=UTF-8 -Dcapsule.trampoline -Dcapsule.java.cmd="$JAVA_CMD" -Dcom.sun.security.enableAIAcaIssuers=true)
 if [[ $cmd == console ]]; then bg=1;
 else JAVA_OPTS+=(-Djava.awt.headless=true)
 fi
 
-[[ "$NXF_MODE" ]] && JAVA_OPTS+=(-Dcapsule.mode=$NXF_MODE)
+[[ "$JAVA_VER" =~ ^(21) ]] && [[ ! "$NXF_ENABLE_VIRTUAL_THREADS" ]] && NXF_ENABLE_VIRTUAL_THREADS=true
 [[ "$JAVA_HOME" ]] && JAVA_OPTS+=(-Dcapsule.java.home="$JAVA_HOME")
 [[ "$CAPSULE_LOG" ]] && JAVA_OPTS+=(-Dcapsule.log=$CAPSULE_LOG)
 [[ "$CAPSULE_RESET" ]] && JAVA_OPTS+=(-Dcapsule.reset=true)
@@ -370,10 +351,13 @@ fi
 [[ "$COLUMNS" ]] && export COLUMNS
 [[ "$NXF_TEMP" ]] && JAVA_OPTS+=(-Djava.io.tmpdir="$NXF_TEMP")
 [[ "${jvmopts[@]}" ]] && JAVA_OPTS+=("${jvmopts[@]}")
-# use drip to speedup startup time -- https://github.com/ninjudd/drip
-[[ "$NXF_DRIP" ]] && export DRIP_INIT='' && export DRIP_INIT_CLASS='nextflow.cli.DripMain'
 export JAVA_CMD
 export CAPSULE_CACHE_DIR
+export NXF_PLUGINS_DIR
+export NXF_PLUGINS_MODE
+export NXF_PLUGINS_DEFAULT
+export NXF_PACK
+export NXF_ENABLE_VIRTUAL_THREADS
 
 # lookup the a `md5` command
 if hash md5sum 2>/dev/null; then MD5=md5sum;
@@ -400,29 +384,42 @@ $NXF_VER
 $NXF_OPTS
 $NXF_GRAB
 $NXF_CLASSPATH
-$NXF_DRIP
+$NXF_JVM_ARGS
+$NXF_ENABLE_VIRTUAL_THREADS
 EOF
 }
 
 # checked if a cached classpath file exists and it newer that the nextflow boot jar file
-if [[ -f /.nextflow/dockerized ]]; then
-  LAUNCH_FILE=/.nextflow/launch-classpath
-else
-  LAUNCH_FILE="${NXF_LAUNCHER}/classpath-$(env_md5)"
-fi
-if [ -s "$LAUNCH_FILE" ] && [ "$LAUNCH_FILE" -nt "$NXF_BIN" ]; then
-    launcher=($(cat "$LAUNCH_FILE"))
+LAUNCH_FILE="${NXF_LAUNCHER}/classpath-$(env_md5)"
+
+if [ -s "$LAUNCH_FILE" ] && [ "$LAUNCH_FILE" -nt "$NXF_BIN" ] && [[ "$remote_debug" -ne 1 ]]; then
+    declare -a launcher="($(cat "$LAUNCH_FILE"))"
 else
     # otherwise run the capsule and get the result classpath in the 'launcher' and save it to a file
     cli=($("$JAVA_CMD" "${JAVA_OPTS[@]}" -jar "$NXF_BIN"))
-    [[ $? -ne 0 ]] && echo_red 'Unable to initialize nextflow environment' && exit $?
+    [[ $? -ne 0 ]] && echo_red 'Unable to initialize nextflow environment' && exit 1
 
-    if [[ "$JAVA_VER" =~ ^(9|10|11) ]]; then
-      launcher=("${cli[@]:0:1}")
+    # first string between double quotes is the full path to java, also blank spaces are included
+    # remainder string are arguments
+    # we extract first part into `cmd_base`` and remainder into `cmd_tail`` and convert them to array as previous version
+    cmd_pattern='"([^"]*)"(.*)'
+    [[ "${cli[@]}" =~ $cmd_pattern ]]
+    cmd_base=(${BASH_REMATCH[1]})
+    cmd_tail=(${BASH_REMATCH[2]})
+
+    launcher="${cmd_base[@]}"
+    [[ "$NXF_JVM_ARGS" ]] && launcher+=($NXF_JVM_ARGS)
+    [[ "$remote_debug" ]] && launcher+=(-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=$NXF_REMOTE_DEBUG_PORT)
+
+    if [[ "$JAVA_VER" =~ ^(9|10|11|12|13|14|15|16|17|18|19|20|21) ]]; then
       launcher+=(--add-opens=java.base/java.lang=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/java.io=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/java.nio=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.net=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/java.util=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.nio.file.spi=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/sun.nio.ch=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/sun.nio.fs=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/sun.net.www.protocol.http=ALL-UNNAMED)
@@ -430,17 +427,23 @@ else
       launcher+=(--add-opens=java.base/sun.net.www.protocol.ftp=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/sun.net.www.protocol.file=ALL-UNNAMED)
       launcher+=(--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED)
-      launcher+=(--illegal-access=deny)
-      launcher+=("${cli[@]:1}")
+      launcher+=(--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED)
+      launcher+=(--add-opens=java.base/java.util.regex=ALL-UNNAMED)
+      if [[ "$NXF_ENABLE_VIRTUAL_THREADS" == 'true' ]]; then
+        if [[ "$JAVA_VER" =~ ^(19|20) ]]; then launcher+=(--enable-preview)
+        elif [[ ! "$JAVA_VER" =~ ^(21) ]]; then die "Virtual threads require Java 19 or later - current version $JAVA_VER"
+        fi
+      fi
+      launcher+=("${cmd_tail[@]}")
     else
-      launcher=("${cli[@]}")
+      launcher+=("${cmd_tail[@]}")
     fi
 
     # Don't show errors if the LAUNCH_FILE can't be created
     if mkdir -p "${NXF_LAUNCHER}" 2>/dev/null; then
         STR=''
         for x in "${launcher[@]}"; do
-        [[ "$x" != "\"-Duser.dir=$PWD\"" ]] && STR+="$x "
+        [[ "$x" != "\"-Duser.dir=$PWD\"" ]] && [[ ! "$x" == *"-agentlib:jdwp"* ]] && STR+="$x "
         done
         printf "$STR">"$LAUNCH_FILE"
     else
@@ -449,5 +452,7 @@ else
 
 fi
 
+# check for latest version
+check_latest
 # finally run it
 launch_nextflow
